### ISSUE TITLE
Remove language specific validation errors

### ISSUE THREAD

**Issue by birchamp** [unfoldingWord/gateway-admin#81] opened 2022-02-02 16:44 UTC
Language specific, punctuation and grammar errors should not be included in validation.

**Comment by mandolyte** [comment] 2022-02-03 14:50
Duplicate of #69

**Comment by mandolyte** [comment] 2022-02-08 14:42
I plan to do this without actually changing how the uw-content-validation package works. There is a cvFilter() function that is used to suppress certain rows. I will add some logic to this function to exclude Spanish punctuation notices. 

Probably not a long term fix, since non-Latin scripts may cause even more issues. Which may necessitate an overhaul to how CV works.

@birchamp

**Closed** 2022-02-08 15:06 UTC
Labels: duplicate

**Comment by birchamp** [comment] 2022-02-08 15:59
I like this as a mid term fix
